server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: spring-boot-template-project

  datasource:
    url: jdbc:postgresql://localhost:5432/log
    username: root
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
zuul:
  servlet-path: /zuulTest

minio:
  url: http://localhost:9000
#  access-key: minio
#  access-secret: minio123
  access-key: 3q7GggCjIzCiXk3DBPlI
  access-secret: EmJP4E1jL2IGKh1cK25hKoxen9oPvCe7blPUqbKk


